### ISSUE TITLE
`nmz inspectors proc -cmd ...` lacks stdio

### ISSUE THREAD

**Issue by AkihiroSuda** [osrg/namazu#152]
https://github.com/osrg/namazu/pull/151 introduced `nmz inspectors proc -cmd ...`, but it lacks stdio.

how to reproduce the issue:
```
$ ./namazu/bin/nmz inspectors proc -cmd yes
```

expected output:
```
y
y
y
y
y
..
```

actual output: (empty)

PTAL @mitake

**Comment by mitake** [comment]
I'll add an option for controlling stdout tomorrow.
