### ISSUE TITLE
Can not get mflag:Docker has been removed pkg/mflag 

### ISSUE THREAD

**Issue by nolouch** [osrg/namazu#165]
Ref PR:https://github.com/docker/docker/pull/25354/. Docker has been removed `pkg/mflag` with new cli framework . new user can not build namazu.you may need to fix it.

**Comment by AkihiroSuda** [comment]
thank you for pointing out!
I'll fix that

**Comment by AkihiroSuda** [comment]
#166  should have fixed that, although ideally we should remove dependency for docker
PTAL @nolouch

**Comment by nolouch** [comment]
LGTM thank you
