### ISSUE TITLE
how to stop inspector

### ISSUE THREAD

**Issue by UncP** [osrg/namazu#187]
how can i stop inspector when it started? for example:
> nmz inspectors fs -original-dir ~/tmp -mount-point ~/mnt

is `fusermount -u /mnt` means stoping fuse inspector? if not, is it possible not to use mypolicy.go, just the command line.

**Comment by UncP** [comment]
i found the solution, closing this issue now.

**Comment by AkihiroSuda** [comment]
Please use Ctrl-C to stop.
